# Generated by Django 4.1.3 on 2022-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('title', models.CharField(max_length=150)),
                ('content_html', models.TextField()),
                ('summary', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('date_published', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
